In [2]:
#Addition of two matrices using list

# Create two matrices using nested lists
matrix1 = [
    [1, 2, 3],
    [4, 5, 6]
]

matrix2 = [
    [7, 8, 9],
    [10, 11, 12]
]

# Initialize a result matrix with the same size
result = [
    [0, 0, 0],
    [0, 0, 0]
]

# Perform matrix addition
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] + matrix2[i][j]

# Display Matrix 1
print("Matrix 1:")
for row in matrix1:
    print(row)

# Display Matrix 2
print("\nMatrix 2:")
for row in matrix2:
    print(row)

# Display the result
print("\nSum of Matrix 1 and Matrix 2:")
for row in result:
    print(row)

Matrix 1:
[1, 2, 3]
[4, 5, 6]

Matrix 2:
[7, 8, 9]
[10, 11, 12]

Sum of Matrix 1 and Matrix 2:
[8, 10, 12]
[14, 16, 18]


In [3]:
#Addition of two matrices using NumPy array

import numpy as np

# Create two matrices using NumPy arrays
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

# Add the two matrices
res = a + b

# Display the result
print("Matrix 1:")
print(a)

print("\nMatrix 2:")
print(b)

print("\nSum of Matrix 1 and Matrix 2:")
print(res)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Sum of Matrix 1 and Matrix 2:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
